### PR TITLE
Closable Dropdown: Pass control to calling component 

### PR DESCRIPTION
**Pull request by valoricDe**
can use useRef to save function pointer in calling component

### CODE REVIEW

**Comment by valoricDe** [comment]
@sajadevo Exaclty it is possible to close the dropdown by clicking outside of the Dropdown. But what is missing is that you can close the Dropdown when clicking on some components outside of the Dropdown components. Let's say DropdownItem for example. I open the Dropdown, select /onClick a DropdownItem/Link and want to close the hole Dropdown.

**Comment by valoricDe** [comment]
@sajadevo were you able to look at my comment from above? Beeing able to close a dropdown on action is a pretty common behaviour I guess. Another possibility would be to do it like material ui does it: https://material-ui.com/components/menus/

**Comment by sajadevo** [comment]
@valoricDe for now its not what we want to have on material tailwind, currently material tailwind is on its beta version not the stable version and we are working on its feature updates I will add your PR to your code if we need it.

**Comment by valoricDe** [comment]
Alright. Thanks for getting back. Have a good day

**Pull request closed without merging**
