### PR TITLE
📝 Added link to install Tailwind before installing Material Tailwind

### PR DESCRIPTION
**Pull request by max-programming**
I started installing Material Tailwind and I forgot to install Tailwind CSS beforehand.

This is a reminder for users to first install Tailwind and then install Material Tailwind to set it up and make it work properly.

I hope it helps :v:

### CODE REVIEW

**Review by sajadevo — APPROVED** [review]

**Comment by sajadevo** [comment]
Hi @max-programming,

Thanks for contributing to Material Tailwind, could you please read the contributions guideline and then make your PR based on that.

Cheers,
Sajad

**Comment by max-programming** [comment]
Is it okay if I don't make separate branches and pull requests `(different for html and react)`? 
As everything is already included in this PR?

**Comment by sajadevo** [comment]
> Is it okay if I don't make separate branches and pull requests `(different for html and react)`? As everything is already included in this PR?

Yup its okey just the PR should be first on dev-main branch.

**Comment by max-programming** [comment]
Gotcha ✌️

**Review by sajadevo — APPROVED** [review]

**Pull request merged**
