### PR TITLE
Dev main

### PR DESCRIPTION
**Pull request by Ianodad**
Ability to pass className as props for cards. This will allow devs to add additional compatible tailwind CSS classes or custom classes for a more customized UI experience.

### CODE REVIEW

**Comment by sajadevo** [comment]
Hello @lanodad thanks for contributing to Material Tailwind project, we really appreciate your work but the idea is that we want to make the components the same as we design and user can just use it and adjust it using props.
Material Tailwind doesn't contain all of the css classes we just compile the classes that we have used for the project.

But anyway thanks for your contribution but for now we don't want to make these components more customizable for users because it will cause some UX flaws, but for the future plan if we want to have something like this we will contact with you.

**All the best,**
**Sajad**

**Comment by Ianodad** [comment]
Hello Sajad
I appreciate the feedback. I thought as much after viewing the codebase. I
will try out some features based on that criteria and give it a go.

**Comment by sajadevo** [comment]
Hey @lanodad
Thats awesome looking forward to your amazing feedbacks keep it on. ❤️🙏
We will get a decision about the custom className for the components.

**All the best**
**Sajad**

**Comment by Arnaud-Desportes** [comment]
> Hello @lanodad thanks for contributing to Material Tailwind project, we really appreciate your work but the idea is that we want to make the components the same as we design and user can just use it and adjust it using props. Material Tailwind doesn't contain all of the css classes we just compile the classes that we have used for the project.
> 
> But anyway thanks for your contribution but for now we don't want to make these components more customizable for users because it will cause some UX flaws, but for the future plan if we want to have something like this we will contact with you.
> 
> **All the best,** **Sajad**

It's a pity I have the impression that your library overloads my initial tailwind.config.js file with the material-tailwind one which makes the customization totally ineffective, no? Did I miss something? Why not allow customization, it makes no sense to use tailwind!

**Comment by sajadevo** [comment]
**Hi there**

For the current version you can customize the tailwind.config.js file but we will make this one possible on the next update of the product.

**All the best,
Sajad**

**Pull request closed without merging**
