### PR TITLE
FIX: Props interface was created but never used

### PR DESCRIPTION
**Pull request by Deveesh-Shetty**
In that file props interface was created but was never used to type define the component props.

My first pull request....still learning hope the thing i did was correct

### CODE REVIEW

**Comment by Deveesh-Shetty** [comment]
I have changed the branch to `dev-main` but I don't know how to add you as a reviewer... would be great if u guide me to that 😅

**Comment by sajadevo** [comment]
> I have changed the branch to `dev-main` but I don't know how to add you as a reviewer... would be great if u guide me to that 😅

On the right hand corner click the settings icon.

Screenshot 2022-12-05 at 22 45 47

**Comment by Deveesh-Shetty** [comment]
image
there is no settings icon here

**Comment by sajadevo** [comment]
Alright @Deveesh-Shetty thanks for the updates I'll merge your changes with the new update that I'm working on.

Cheers,
Sajad

**Comment by Deveesh-Shetty** [comment]
Great! Thank you for helping, it is my first contribution to open-source project :)

**Review by sajadevo — APPROVED** [review]

**Pull request closed without merging**
